### ISSUE TITLE
app.js missing a listen function

### ISSUE THREAD

**Issue by farmanp** [simonholmes/MEAN-stack-authentication#1]
The app wasn't running properly and needs this in the app.js file: 

app.listen(27017, function (){});

**Comment by simonholmes** [comment]
Port 27017 is the default one used by MongoDB localhost server. If you have MongoDB running locally and try to listen to port 27017 from your Express app you'll get a conflict as MongoDB is already running. 

If your MongoDB service is running on a different port then you'll need to change the database connection string.

Alternatively, if you were having issues and this prevented some of them, it might be that your MongoDB service wasn't running.

Hope that helps.
